services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/financial_advisor.db:/app/financial_advisor.db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://host.docker.internal:8000
    depends_on:
      - backend
    restart: unless-stopped
