services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./financial_advisor.db:/app/financial_advisor.db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
      args:
        VITE_API_BASE_URL: http://backend:8000
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
